Porting mechanics to new architecture
wareHHOuse/diskpp pull request #104
Opened 2024-02-12 21:37 UTC by npaster

Hi,

I have ported the mechanical module to the new architecture. 

I have also fixed some warning. I can't compile diffusion without mumps

In a soon future, I will update basis functions (to add recent works in the old basis) and quadrature for very distorted polygons

2024-05-01 17:15 UTC, datafl4sh requested changes
Hello @npaster . I reviewed all the changes, thank you for your huge work. I have two major remarks. The first is to please do not use tools that automatically reformat the code: they add a lot of noise, and reviewing the changes becomes very hard. It is easy to miss some bugs in the middle of all the formatting changes. The second is that some functions were removed from `hho_degree_info` and this breaks lots of stuff. Please be sure to do a full compile.

2024-05-01 17:15 UTC, datafl4sh commented on libdiskpp/include/diskpp/quadratures/bits/quad_raw_gauss.hpp
Please restore the old formatting for this file, especially for the quadrature points data.

2024-05-01 17:15 UTC, datafl4sh commented on libdiskpp/include/diskpp/quadratures/bits/quad_raw_tetra.hpp
> +static const double arbq_to_ref_A[3][3] = {{0.500000000000000, -0.288675134594813, -0.204124145231932},
Please restore old formatting for `arbq_to_ref_A`.

2024-05-03 13:25 UTC, npaster commented
> Hello @npaster . I noticed that you sent a PR, but in the last months I was really busy...teaching and stuff...so I wasn't working on code at all. Sorry for the delay, and thank you for your work. I am going to merge it.

Hello Matteo,

Thank you for your review.

I am going to modify my code next week. I will try to remove my automatic reformatting

2024-06-07 14:52 UTC, npaster commented
I hope that everything is fixed.

My compiler is not fully c++20 compatible and I have many errors

I have also a lot with mumps (I don't have mumps locally)

/diskpp/apps/diffusion/src/diffusion_vem.cpp:138:12: error: use of undeclared identifier 'mumps_lu'
    csol = mumps_lu(LHS, RHS);

2024-09-18 12:35 UTC, merged